name: NFT
on: [pull_request]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        id: go
        with:
          go-version: 1.14
      - name: Setup env for GO
        #  this is only used until the setup-go action is updated
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash
      - uses: actions/checkout@v2
      - name: Unit_test
        run: cd incubator/nft && make test
